const MUSCLE_NAMES={chest:'Chest',frontDelts:'Front Delts',sideDelts:'Side Delts',rearDelts:'Rear Delts',biceps:'Biceps',triceps:'Triceps',forearms:'Forearms',abs:'Abs',quads:'Quads',adductors:'Adductors',calves:'Calves',lats:'Lats',upperBack:'Upper Back',traps:'Traps',glutes:'Glutes',hamstrings:'Hamstrings',lowerBack:'Lower Back'};
const MUSCLE_BY_EXERCISE={
'Lying Leg Curl':['hamstrings'],'Seated Leg Curl':['hamstrings'],'Nordic Ham Curl':['hamstrings'],
'Squat (Your Choice)':['quads','glutes','adductors'],'Hack Squat':['quads','glutes'],'Leg Press':['quads','glutes'],'Barbell Squat':['quads','glutes'],
'Barbell Incline Press':['chest','frontDelts','triceps'],'Smith Machine Incline Press':['chest','frontDelts','triceps'],'DB Incline Press':['chest','frontDelts','triceps'],'Machine Chest Press':['chest','frontDelts','triceps'],'DB Bench Press':['chest','frontDelts','triceps'],'Smith Machine Bench Press':['chest','frontDelts','triceps'],
'Incline DB Y-Raise':['sideDelts','rearDelts'],'Cable Y-Raise':['sideDelts','rearDelts'],'Machine Lateral Raise':['sideDelts'],'High-Cable Lateral Raise':['sideDelts'],'DB Lateral Raise':['sideDelts'],
'Pull-Up (Wide Grip)':['lats','biceps'],'Lat Pulldown (Wide Grip)':['lats','biceps'],'1-Arm Cable Pulldown':['lats','biceps'],'Close-Grip Lat Pulldown':['lats','biceps'],'Close-Grip Pull-Up':['lats','biceps'],
'Standing Calf Raise':['calves'],'Leg Press Calf Press':['calves'],'Donkey Calf Raise':['calves'],
'Chest-Supported T-Bar Row':['upperBack','lats','rearDelts','biceps'],'Chest-Supported Machine Row':['upperBack','lats','rearDelts','biceps'],'Chest-Supported DB Row':['upperBack','lats','rearDelts','biceps'],
'Machine Shrug':['traps'],'Barbell Shrug':['traps'],'Cable Shrug-In':['traps'],
'1-Arm Reverse Pec Deck':['rearDelts','upperBack'],'Lying Reverse DB Flye':['rearDelts','upperBack'],'Reverse Cable Crossover':['rearDelts','upperBack'],
'Cable Crunch':['abs'],'Weighted Crunch':['abs'],'Machine Crunch':['abs'],
'Leg Extension':['quads'],'Reverse Nordic':['quads'],'Sissy Squat':['quads'],
'Barbell RDL':['hamstrings','glutes','lowerBack'],'DB RDL':['hamstrings','glutes','lowerBack'],'Seated Cable Deadlift':['hamstrings','glutes','lowerBack'],
'Machine Hip Thrust':['glutes','hamstrings'],'Barbell Hip Thrust':['glutes','hamstrings'],'45° Hyperextension':['glutes','hamstrings','lowerBack'],
'Bayesian Cable Curl':['biceps'],'Incline DB Curl':['biceps'],'Standing DB Curl':['biceps'],'Modified Zottman Curl':['biceps','forearms'],'DB Hammer Curl':['biceps','forearms'],'Preacher Hammer Curl':['biceps','forearms'],'Alternating DB Curl':['biceps'],'Barbell Curl':['biceps'],'EZ-Bar Curl':['biceps'],
'Overhead Cable Triceps Extension':['triceps'],'Overhead DB Triceps Extension':['triceps'],'Skull Crusher':['triceps'],'Cable Triceps Kickback':['triceps'],'Seated Dip Machine':['triceps'],'Close-Grip Dip':['triceps'],
'DB Wrist Curl':['forearms'],'Cable Wrist Curl':['forearms'],'DB Wrist Extension':['forearms'],'Cable Wrist Extension':['forearms'],'Dead Hang (optional)':['forearms','lats']
};
function xesc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function xdownload(blob,name){let a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function xtraining(r){return (r&&r.sets?r.sets:[]).filter(s=>s.type!=='Warmup')}
function xperformed(r){return xtraining(r).some(s=>String(s.load||'').trim()||String(s.reps||'').trim())}
function xmaxLoad(r){return Math.max(0,...xtraining(r).map(s=>+s.load||0))}
function xvol(r){return xtraining(r).reduce((a,s)=>a+(+s.load||0)*(+s.reps||0),0)}
function xe1(r){return Math.max(0,...xtraining(r).map(s=>(+s.load||0)*(1+(+s.reps||0)/30)))}
function xopts(e){return [{name:e.name,link:e.link||''}].concat((e.alts||[]).filter(a=>a.name))}
function xselected(e,k){return xopts(e)[+(state.swaps&&state.swaps[k]||0)]||xopts(e)[0]}
function xmuscles(e,k){let sel=xselected(e,k).name;return e.muscles||MUSCLE_BY_EXERCISE[sel]||MUSCLE_BY_EXERCISE[e.name]||[]}
function flattenRows(){let rows=[];for(let w=1;w<=12;w++){for(let s=0;s<SESS.length;s++){(BASE[SESS[s][1]]||[]).forEach((e,i)=>{let k=`w${w}s${s}e${i}`,r=state.logs[k]||{},sel=xselected(e,k);(r.sets||[]).forEach((set,idx)=>rows.push(rowObj(w,s,sel.name,e.name,'No',xmuscles(e,k),idx,set,r,e)))});(state.custom[`w${w}s${s}`]||[]).forEach((e,i)=>{let k=`w${w}s${s}c${i}`,r=state.logs[k]||{};(r.sets||[]).forEach((set,idx)=>rows.push(rowObj(w,s,e.name,e.name,'Yes',e.muscles||[],idx,set,r,e)))})}}return rows}
function rowObj(w,s,ex,base,manual,muscles,idx,set,r,e){return {Week:w,Day:SESS[s][0],Tab:SESS[s][1],Exercise:ex,BaseExercise:base,Manual:manual,Muscles:(muscles||[]).map(m=>MUSCLE_NAMES[m]||m).join('; '),SetNumber:idx+1,SetType:set.type||'',Load:set.load||'',Reps:set.reps||'',RIR:set.rir||'',WarmupGuidance:e.warmup||'',WorkingSetTarget:e.sets||'',RepTarget:e.reps||'',Rest:e.rest||'',Notes:r.notes||''}}
function csvEscape(v){let s=String(v??'');return /[",\n]/.test(s)?'"'+s.replace(/"/g,'""')+'"':s}
window.exportCSV=()=>{let rows=flattenRows(),heads=Object.keys(rows[0]||rowObj('','','','','','',0,{}, {},{}));let csv=[heads.join(',')].concat(rows.map(r=>heads.map(h=>csvEscape(r[h])).join(','))).join('\n');xdownload(new Blob([csv],{type:'text/csv;charset=utf-8'}),'min-max-tracker-export.csv')}
window.exportExcel=()=>{let rows=flattenRows(),heads=Object.keys(rows[0]||rowObj('','','','','','',0,{}, {},{}));let html='<html><head><meta charset="utf-8"></head><body><table border="1"><tr>'+heads.map(h=>`<th>${xesc(h)}</th>`).join('')+'</tr>'+rows.map(r=>'<tr>'+heads.map(h=>`<td>${xesc(r[h])}</td>`).join('')+'</tr>').join('')+'</table></body></html>';xdownload(new Blob([html],{type:'application/vnd.ms-excel'}),'min-max-tracker-export.xls')}
window.exportBackup=()=>xdownload(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),'min-max-tracker-backup.json');
window.saveToPhone=()=>window.exportBackup();
window.importFile=()=>document.getElementById('importer').click();
function heatColor(week){if(!week)return'rgba(255,255,255,.03)';let t=(week-1)/11,h=120-120*t,l=32+18*t;return`hsl(${h} 78% ${l}%)`}
function musclesByWeek(){let data={};for(let w=1;w<=12;w++){for(let s=0;s<SESS.length;s++){(BASE[SESS[s][1]]||[]).forEach((e,i)=>{let k=`w${w}s${s}e${i}`,r=state.logs[k]||{};if(xperformed(r))xmuscles(e,k).forEach(m=>data[m]=Math.max(data[m]||0,w))});(state.custom[`w${w}s${s}`]||[]).forEach((e,i)=>{let r=state.logs[`w${w}s${s}c${i}`]||{};if(xperformed(r))(e.muscles||[]).forEach(m=>data[m]=Math.max(data[m]||0,w))})}}return data}
function frontSvg(){return`<svg class="bodySvg" viewBox="0 0 240 500"><circle cx="120" cy="35" r="24" fill="rgba(255,255,255,.06)" stroke="var(--line)"/><rect x="96" y="58" width="48" height="46" rx="20" fill="rgba(255,255,255,.04)" stroke="var(--line)"/><ellipse data-muscle="frontDelts" cx="82" cy="95" rx="18" ry="20"/><ellipse data-muscle="frontDelts" cx="158" cy="95" rx="18" ry="20"/><ellipse data-muscle="chest" cx="98" cy="118" rx="28" ry="24"/><ellipse data-muscle="chest" cx="142" cy="118" rx="28" ry="24"/><rect data-muscle="biceps" x="54" y="110" width="18" height="60" rx="8"/><rect data-muscle="biceps" x="168" y="110" width="18" height="60" rx="8"/><rect data-muscle="forearms" x="48" y="170" width="14" height="78" rx="8"/><rect data-muscle="forearms" x="178" y="170" width="14" height="78" rx="8"/><rect data-muscle="abs" x="100" y="145" width="16" height="22" rx="5"/><rect data-muscle="abs" x="124" y="145" width="16" height="22" rx="5"/><rect data-muscle="abs" x="100" y="173" width="16" height="22" rx="5"/><rect data-muscle="abs" x="124" y="173" width="16" height="22" rx="5"/><rect data-muscle="abs" x="100" y="201" width="16" height="22" rx="5"/><rect data-muscle="abs" x="124" y="201" width="16" height="22" rx="5"/><ellipse data-muscle="adductors" cx="110" cy="284" rx="12" ry="38"/><ellipse data-muscle="adductors" cx="130" cy="284" rx="12" ry="38"/><ellipse data-muscle="quads" cx="94" cy="300" rx="22" ry="58"/><ellipse data-muscle="quads" cx="146" cy="300" rx="22" ry="58"/><ellipse data-muscle="calves" cx="102" cy="410" rx="16" ry="48"/><ellipse data-muscle="calves" cx="138" cy="410" rx="16" ry="48"/></svg>`}
function backSvg(){return`<svg class="bodySvg" viewBox="0 0 240 500"><circle cx="120" cy="35" r="24" fill="rgba(255,255,255,.06)" stroke="var(--line)"/><rect x="96" y="58" width="48" height="46" rx="20" fill="rgba(255,255,255,.04)" stroke="var(--line)"/><polygon data-muscle="traps" points="95,92 120,66 145,92 135,122 105,122"/><ellipse data-muscle="rearDelts" cx="82" cy="100" rx="18" ry="18"/><ellipse data-muscle="rearDelts" cx="158" cy="100" rx="18" ry="18"/><polygon data-muscle="upperBack" points="88,118 120,132 152,118 145,180 95,180"/><polygon data-muscle="lats" points="72,126 94,136 90,226 60,195"/><polygon data-muscle="lats" points="168,126 146,136 150,226 180,195"/><rect data-muscle="triceps" x="50" y="116" width="18" height="72" rx="8"/><rect data-muscle="triceps" x="172" y="116" width="18" height="72" rx="8"/><rect data-muscle="forearms" x="43" y="190" width="14" height="82" rx="8"/><rect data-muscle="forearms" x="183" y="190" width="14" height="82" rx="8"/><rect data-muscle="lowerBack" x="106" y="182" width="28" height="52" rx="9"/><ellipse data-muscle="glutes" cx="102" cy="262" rx="24" ry="26"/><ellipse data-muscle="glutes" cx="138" cy="262" rx="24" ry="26"/><ellipse data-muscle="hamstrings" cx="98" cy="334" rx="20" ry="56"/><ellipse data-muscle="hamstrings" cx="142" cy="334" rx="20" ry="56"/><ellipse data-muscle="calves" cx="102" cy="420" rx="16" ry="48"/><ellipse data-muscle="calves" cx="138" cy="420" rx="16" ry="48"/></svg>`}
function bodyHeatSection(){return`<div class=card><div class=title>Muscle Map</div><p class=meta>Muscles change from green toward red as you train them in later weeks. No colour means not logged yet.</p><div class=bodyWrap><div class=bodyCard><div class=bodyTitle>Front</div>${frontSvg()}</div><div class=bodyCard><div class=bodyTitle>Back</div>${backSvg()}</div></div><div class=legend>${[1,3,5,7,9,12].map(w=>`<div style="border-color:${heatColor(w)};color:${heatColor(w)}">W${w}</div>`).join('')}</div></div>`}
function applyMuscleHeat(){let map=musclesByWeek();document.querySelectorAll('[data-muscle]').forEach(el=>{let m=el.getAttribute('data-muscle');el.style.fill=heatColor(map[m]||0)})}
function xvolume(){let arr=Array(12).fill(0);for(let w=1;w<=12;w++)for(let s=0;s<SESS.length;s++){(BASE[SESS[s][1]]||[]).forEach((e,i)=>arr[w-1]+=xvol(state.logs[`w${w}s${s}e${i}`]||{}));(state.custom[`w${w}s${s}`]||[]).forEach((e,i)=>arr[w-1]+=xvol(state.logs[`w${w}s${s}c${i}`]||{}))}return arr}
renderAnalytics=function(){let vols=xvolume(),total=Math.round(vols.reduce((a,b)=>a+b,0)),best=0;Object.values(state.logs).forEach(r=>best=Math.max(best,xe1(r)));let rows=exerciseProgress();let h=`<div class=card><div class=title>Analytics</div><p class=meta>Training volume excludes warmup sets. Body map uses logged working and extra sets.</p></div><div class=kpis><div class=kpi><b>${total}</b><br><span class=meta>Total working volume</span></div><div class=kpi><b>${Math.round(best)}</b><br><span class=meta>Best e1RM</span></div></div><div class=card><div class=title>Weekly Volume</div><div id=volChart></div></div><div class=card><div class=title>Bodyweight</div><div id=bwChart></div></div>${bodyHeatSection()}<div class=card><div class=title>Weight Increase by Exercise</div><p class=meta>Compares first recorded training-set load to latest recorded training-set load.</p><div class=exerciseProgress>`;h+=rows.length?rows.map(r=>`<div class=progressRow><b>${xesc(r.name)}</b><span>${xesc(r.day)} • first: ${r.first} ${xesc(state.units)} (W${r.firstW}) → latest: ${r.last} ${xesc(state.units)} (W${r.lastW})</span><span>Change: ${r.change>=0?'+':''}${r.change} ${xesc(state.units)} • Best: ${r.best} ${xesc(state.units)}</span></div>`).join(''):'<p class=meta>No logged lifting weight yet.</p>';h+='</div></div>';$('analytics').innerHTML=h;$('volChart').appendChild(chart(vols));$('bwChart').appendChild(chart(Array.from({length:12},(_,i)=>+state.bw[i+1]||0)));applyMuscleHeat()}
renderSettings=function(){let h=`<div class=card><div class=title>Local Saving</div><p class=meta>The app auto-saves locally. Use Save to Phone File for a real backup outside browser storage.</p><div class=exportGrid><button class=primary onclick="save(true)">Save Now</button><button onclick="saveToPhone()">Save to Phone File</button><button onclick="importFile()">Load Backup File</button><button onclick="exportBackup()">Export JSON</button></div></div><div class=card><div class=title>Export</div><p class=meta>Export your log as CSV or Excel-compatible XLS.</p><div class=exportGrid><button onclick="exportCSV()">Export CSV</button><button onclick="exportExcel()">Export Excel</button></div></div>`;h+=`<div class=card><div class=title>Colour Scheme</div><p class=meta>Choose a preset, or customize individual page colours.</p><div class=palette>`;Object.keys(THEMES).forEach(k=>h+=`<button class="${!state.customTheme&&state.theme===k?'active':''}" onclick="setTheme('${k}')">${THEMES[k].name}</button>`);h+='</div></div>';h+=`<div class=card><div class=title>Backup + Settings</div><p class=meta>Data saves locally on this phone/browser. Export a backup occasionally.</p><label>Units</label><select onchange="state.units=this.value;save(true);renderWorkout()"><option ${state.units==='lb'?'selected':''}>lb</option><option ${state.units==='kg'?'selected':''}>kg</option></select></div>`;$('settings').innerHTML=h}
const oldImport=document.getElementById('importer');if(oldImport){oldImport.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=Object.assign(state,JSON.parse(r.result));if(!state.swaps)state.swaps={};if(!state.custom)state.custom={};save(true);applyTheme();renderAll()}catch(err){toast('Import failed')}};r.readAsText(f)}}
setTimeout(()=>{if(typeof currentView==='undefined'||document.getElementById('analytics')&&!document.getElementById('analytics').classList.contains('hidden'))renderAnalytics();},300);