// Advanced polish features: next workout, set done checks, rest timer, previous comparison,
// progression recommendations, block 2 intensity notes, exercise history, autofill warmups,
// weekly summaries, discomfort tracking, measurements, muscle volume analytics, setup help.
(function(){
  function E(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function n(v){let x=parseFloat(v);return isFinite(x)?x:0}
  function dk(w=state.week,s=state.session){return `w${w}s${s}`}
  function bk(i,w=state.week,s=state.session){return `w${w}s${s}e${i}`}
  function ck(i,w=state.week,s=state.session){return `w${w}s${s}c${i}`}
  function ensure(){ if(!state.done)state.done={}; if(!state.pain)state.pain={}; if(!state.measure)state.measure={}; if(!state.photos)state.photos={}; if(!state.lastSession)state.lastSession=null; }
  function persist(){ensure(); save();}
  function workSets(r){return (r&&r.sets?r.sets:[]).filter(x=>x.type!=='Warmup')}
  function hasLog(r){return workSets(r).some(s=>String(s.load||'').trim()||String(s.reps||'').trim())}
  function allExercisesFor(s=state.session){return (BASE[SESS[s][1]]||[])}
  function currentExerciseKey(i,isCustom=false){return isCustom?ck(i):bk(i)}
  function exerciseDone(k,idx){ensure();return !!state.done[`${k}_${idx}`]}
  window.toggleDone=(k,idx)=>{ensure();let x=`${k}_${idx}`;state.done[x]=!state.done[x];persist();renderWorkout()}
  window.markSessionComplete=()=>{ensure();state.lastSession={week:state.week,session:state.session,at:new Date().toISOString()};persist();toast('Workout marked complete')}
  window.goNextWorkout=()=>{let next=nextSession();state.week=next.week;state.session=next.session;persist();renderWorkout()}
  function nextSession(){ensure();let l=state.lastSession;if(!l)return {week:state.week,session:state.session};let s=+l.session+1,w=+l.week;if(s>=SESS.length){s=0;w=Math.min(12,w+1)}return {week:w,session:s}}
  function nextWorkoutCard(){let nx=nextSession();return `<div class="card warningCard"><div class=title>Today’s Workout</div><p class=meta>Suggested next session: <b>Week ${nx.week} • ${E(SESS[nx.session][0])}</b></p><div class=quickbar><button class=primary onclick="goNextWorkout()">Open Suggested</button><button onclick="markSessionComplete()">Mark Current Complete</button></div></div>`}
  function doneButtons(k,r){let sets=(r.sets||[]);return `<div class=doneGrid>${sets.map((s,i)=>`<button class="${exerciseDone(k,i)?'done':''}" onclick="toggleDone('${k}',${i})">${exerciseDone(k,i)?'✓ ':''}Set ${i+1}</button>`).join('')}</div>`}
  let timerInt=null,timerRemain=0;
  window.startRest=(sec)=>{timerRemain=sec;showTimer();clearInterval(timerInt);timerInt=setInterval(()=>{timerRemain--;showTimer();if(timerRemain<=0){clearInterval(timerInt);toast('Rest complete')}},1000)}
  window.stopRest=()=>{clearInterval(timerInt);let el=document.getElementById('restTimer');if(el)el.remove()}
  function showTimer(){let el=document.getElementById('restTimer');if(!el){el=document.createElement('div');el.id='restTimer';el.className='timer';document.body.appendChild(el)}let m=Math.floor(timerRemain/60),s=String(timerRemain%60).padStart(2,'0');el.innerHTML=`Rest Timer: ${m}:${s}<br><button onclick="stopRest()">Stop</button>`}
  function restSeconds(rest){let m=String(rest||'').match(/(\d+)/g);if(!m)return 90;return (+m[m.length-1])*60}
  function restButtons(e){let base=restSeconds(e.rest);return `<div class=quickbar><button onclick="startRest(${base})">Start ${Math.round(base/60)} min Rest</button><button onclick="startRest(90)">90 sec Rest</button></div>`}
  function lastLoggedForExercise(baseIndex){for(let w=state.week;w>=1;w--){for(let s=SESS.length-1;s>=0;s--){if(w===state.week&&s>=state.session)continue;let r=state.logs[`w${w}s${s}e${baseIndex}`];if(r&&hasLog(r))return {w,s,r}}}return null}
  function lastComparison(baseIndex){let l=lastLoggedForExercise(baseIndex);if(!l)return '<p class=meta>No previous logged set for this exercise yet.</p>';let sets=workSets(l.r).map((x,i)=>`Set ${i+1}: ${x.load||'-'} x ${x.reps||'-'} @ RIR ${x.rir||'-'}`).join(' • ');return `<p class=meta><b>Last time:</b> W${l.w} ${E(SESS[l.s][0])} — ${E(sets)}</p>`}
  function repTop(e){let m=String(e.reps||'').match(/(\d+)\D*(\d+)?/);return m?+(m[2]||m[1]):0}
  function progression(e,r){let top=repTop(e);let sets=workSets(r);if(!top||!sets.length)return 'Log working sets to get a progression suggestion.';let allTop=sets.every(s=>n(s.reps)>=top);let hasLoad=sets.some(s=>n(s.load)>0);if(allTop&&hasLoad)return 'Increase weight next time.';if(hasLoad)return 'Repeat this weight and aim for more reps.';return 'Enter load and reps to generate a recommendation.'}
  function intensity(e){if(state.week<8)return '';let last=e.name==='Machine Chest Press'?'Weighted static hold':(e.name.includes('Curl')||e.name.includes('Raise')||e.name.includes('Extension')?'Myo-reps / lengthened partials':'Drop set / controlled failure');return `<div class=card><div class=title>Block 2 Intensity</div><p class=meta>${E(last)} after the final working set, where appropriate and safe.</p></div>`}
  window.toggleHistory=(id)=>{let el=document.getElementById(id);if(el)el.classList.toggle('show')}
  function historyBox(e,idx){let rows=[];for(let w=1;w<=12;w++)for(let s=0;s<SESS.length;s++){let r=state.logs[`w${w}s${s}e${idx}`];if(r&&hasLog(r))rows.push(`<div class=progressRow><b>W${w} ${E(SESS[s][0])}</b><span>${workSets(r).map((x,i)=>`Set ${i+1}: ${x.load||'-'} x ${x.reps||'-'} RIR ${x.rir||'-'}`).join(' • ')}</span><span>${E(r.notes||'')}</span></div>`)}let id=`hist_${state.week}_${state.session}_${idx}`;return `<button class=miniBtn style="width:100%;margin-top:8px" onclick="toggleHistory('${id}')">Exercise History</button><div id="${id}" class=historyBox>${rows.length?rows.join(''):'<p class=meta>No history yet.</p>'}</div>`}
  window.fillWarmups=(k)=>{let r=state.logs[k];if(!r)return;let work=workSets(r).find(s=>n(s.load)>0);if(!work){toast('Enter working load first');return}let warm=(r.sets||[]).filter(s=>s.type==='Warmup');let pct=[.5,.7,.85,.9];warm.forEach((s,i)=>{s.load=Math.round(n(work.load)*(pct[i]||.5)); if(!s.reps)s.reps=i===0?'6-10':'4-6'});persist();renderWorkout()}
  function painBox(k){ensure();let p=state.pain[k]||{};return `<div class=card><div class=title>Pain / Discomfort</div><div class=manualGrid><div><label>Area</label><input value="${E(p.area||'')}" oninput="state.pain['${k}']=state.pain['${k}']||{};state.pain['${k}'].area=this.value;save()" placeholder="e.g. elbow"></div><div><label>Severity /10</label><input inputmode=decimal value="${E(p.score||'')}" oninput="state.pain['${k}']=state.pain['${k}']||{};state.pain['${k}'].score=this.value;save()"></div></div><label style="margin-top:12px">Pain Notes</label><textarea oninput="state.pain['${k}']=state.pain['${k}']||{};state.pain['${k}'].notes=this.value;save()">${E(p.notes||'')}</textarea></div>`}
  const oldRenderExercise=renderExercise;
  renderExercise=function(e,i,k,isManual){let html=oldRenderExercise(e,i,k,isManual);let r=state.logs[k]||{};let insert=`${doneButtons(k,r)}${!isManual?lastComparison(i):''}<div class=card><div class=title>Progression</div><p class=meta>${E(progression(e,r))}</p><button class=miniBtn style="width:100%" onclick="fillWarmups('${k}')">Auto-fill Warmups from Working Load</button>${restButtons(e)}</div>${!isManual?intensity(e):''}${!isManual?historyBox(e,i):''}${painBox(k)}`;return html.replace('</div>',insert+'</div>')}
  const oldRenderWorkout=renderWorkout;
  renderWorkout=function(){oldRenderWorkout();let sec=$('workout');if(sec){sec.insertAdjacentHTML('afterbegin',nextWorkoutCard())}}
  function weeklySummary(){let w=state.week,workouts=0,sets=0,vol=0,prs=0;for(let s=0;s<SESS.length;s++){let any=false;(BASE[SESS[s][1]]||[]).forEach((e,i)=>{let r=state.logs[`w${w}s${s}e${i}`]||{};if(hasLog(r)){any=true;sets+=workSets(r).length;vol+=workSets(r).reduce((a,x)=>a+n(x.load)*n(x.reps),0)}});if(any)workouts++}return `<div class=card><div class=title>Week ${w} Summary</div><div class=kpis><div class=kpi><b>${workouts}/4</b><br><span class=meta>Workouts logged</span></div><div class=kpi><b>${sets}</b><br><span class=meta>Working sets</span></div><div class=kpi><b>${Math.round(vol)}</b><br><span class=meta>Volume</span></div><div class=kpi><b>${state.bw[w]||'-'}</b><br><span class=meta>Bodyweight</span></div></div></div>`}
  function muscleVolume(){let map={};for(let s=0;s<SESS.length;s++){(BASE[SESS[s][1]]||[]).forEach((e,i)=>{let r=state.logs[`w${state.week}s${s}e${i}`]||{};if(hasLog(r)){let count=workSets(r).length;(e.muscles||MUSCLE_BY_EXERCISE[e.name]||[]).forEach(m=>map[m]=(map[m]||0)+count)}})}let rows=Object.keys(MUSCLE_NAMES).map(m=>`<div class=muscleRow><span>${E(MUSCLE_NAMES[m])}</span><b>${map[m]||0} sets</b></div>`).join('');return `<div class=card><div class=title>Muscle Volume This Week</div><div class=muscleTable>${rows}</div></div>`}
  const oldRenderAnalytics=renderAnalytics;
  renderAnalytics=function(){oldRenderAnalytics();let sec=$('analytics');if(sec)sec.insertAdjacentHTML('afterbegin',weeklySummary()+muscleVolume())}
  window.setMeasure=(f,v)=>{if(!state.measure)state.measure={};state.measure[state.week]=state.measure[state.week]||{};state.measure[state.week][f]=v;save()}
  function measureCard(){let m=(state.measure&&state.measure[state.week])||{};return `<div class=card><div class=title>Measurements + Progress Photo Notes</div><div class=measureGrid><div><label>Waist</label><input value="${E(m.waist||'')}" oninput="setMeasure('waist',this.value)"></div><div><label>Chest</label><input value="${E(m.chest||'')}" oninput="setMeasure('chest',this.value)"></div><div><label>Arms</label><input value="${E(m.arms||'')}" oninput="setMeasure('arms',this.value)"></div><div><label>Thighs</label><input value="${E(m.thighs||'')}" oninput="setMeasure('thighs',this.value)"></div></div><label style="margin-top:12px">Photo Reminder / Notes</label><textarea oninput="setMeasure('photos',this.value)">${E(m.photos||'')}</textarea></div>`}
  const oldSettings=renderSettings;
  renderSettings=function(){oldSettings();let sec=$('settings');if(sec)sec.insertAdjacentHTML('beforeend',measureCard()+`<div class=card><div class=title>Add to Home Screen</div><p class=meta>For best iPhone use: open this app in Safari, tap Share, then Add to Home Screen. Use Save to Phone File weekly as a backup.</p></div>`)}
  setTimeout(()=>{try{renderWorkout();}catch(e){}},500)
})();