// Add-ons: recovery check-in, warm-up calculator, deload reminders, PR badges, and RIR compliance.
(function(){
  function E(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
  function dKey(){return `w${state.week}s${state.session}`}
  function ensure(){ if(!state.recovery)state.recovery={}; if(!state.warmupCalc)state.warmupCalc={load:'',sets:'2'}; }
  function persist(){ ensure(); save(); }
  function num(v){let n=parseFloat(v); return isFinite(n)?n:0}
  function calcWarmups(load,count){ load=num(load); count=parseInt(count||0,10); if(!load||!count)return[]; let p=[]; if(count===1)p=[[60,'6-10']]; if(count===2)p=[[50,'6-10'],[70,'4-6']]; if(count===3)p=[[45,'6-10'],[65,'4-6'],[85,'3-4']]; if(count>=4)p=[[45,'6-10'],[60,'4-6'],[75,'3-5'],[85,'2-4']]; return p.map((x,i)=>({n:i+1,pct:x[0],reps:x[1],load:Math.round(load*x[0]/100)})); }
  window.setRecoveryField=(f,v)=>{ensure(); state.recovery[dKey()]=state.recovery[dKey()]||{}; state.recovery[dKey()][f]=v; persist();};
  window.setWarmupCalc=(f,v)=>{ensure(); state.warmupCalc[f]=v; persist(); renderWorkout();};
  function recoveryCard(){ ensure(); let r=state.recovery[dKey()]||{}; return `<div class=card><div class=title>Recovery Check-In</div><p class=meta>Quick readiness log for this workout.</p><div class=manualGrid><div><label>Sleep /10</label><input inputmode=decimal value="${E(r.sleep||'')}" oninput="setRecoveryField('sleep',this.value)"></div><div><label>Energy /10</label><input inputmode=decimal value="${E(r.energy||'')}" oninput="setRecoveryField('energy',this.value)"></div><div><label>Soreness /10</label><input inputmode=decimal value="${E(r.soreness||'')}" oninput="setRecoveryField('soreness',this.value)"></div><div><label>Stress /10</label><input inputmode=decimal value="${E(r.stress||'')}" oninput="setRecoveryField('stress',this.value)"></div></div><label style="margin-top:12px">Recovery Notes</label><textarea oninput="setRecoveryField('notes',this.value)">${E(r.notes||'')}</textarea></div>`; }
  function deloadCard(){ if(+state.week!==7)return''; return `<div class=card><div class=title>Week 7 Deload Reminder</div><p class=meta>Week 7 is treated as a lighter/deload week. Keep the effort controlled, avoid chasing failure, and use this week to recover while still practicing the movements.</p></div>`; }
  function warmupCard(){ ensure(); let w=state.warmupCalc; let rows=calcWarmups(w.load,w.sets); return `<div class=card><div class=title>Warm-Up Calculator</div><p class=meta>Enter your planned working weight. The calculator estimates exercise-specific warm-up sets.</p><div class=manualGrid><div><label>Working Weight (${E(state.units||'lb')})</label><input inputmode=decimal value="${E(w.load||'')}" oninput="setWarmupCalc('load',this.value)"></div><div><label>Warm-Up Sets</label><select onchange="setWarmupCalc('sets',this.value)"><option ${w.sets==='1'?'selected':''}>1</option><option ${w.sets==='2'?'selected':''}>2</option><option ${w.sets==='3'?'selected':''}>3</option><option ${w.sets==='4'?'selected':''}>4</option></select></div></div><div class=suggList style="margin-top:10px">${rows.length?rows.map(r=>`<div class=item><b>Warm-up ${r.n}: ${r.load} ${E(state.units||'lb')}</b><div class=meta>${r.pct}% of working weight • ${r.reps} reps</div></div>`).join(''):'<div class=item><div class=meta>Add working weight to see warm-up sets.</div></div>'}</div></div>`; }
  const oldRenderWorkout=renderWorkout;
  renderWorkout=function(){ oldRenderWorkout(); let sec=$('workout'); if(!sec)return; let first=sec.querySelector('.card'); if(first) first.insertAdjacentHTML('afterend', deloadCard()+recoveryCard()+warmupCard()); };
  function targetRirFor(e,workIndex){ if(workIndex===0)return e.rir1; if(workIndex===1)return e.rir2; return ''; }
  function rirStats(){ let total=0, ok=0, misses=[]; for(let w=1;w<=12;w++){ for(let s=0;s<SESS.length;s++){ (BASE[SESS[s][1]]||[]).forEach((e,i)=>{ let r=state.logs[`w${w}s${s}e${i}`]||{}; let work=(r.sets||[]).filter(x=>x.type!=='Warmup'); work.forEach((set,wi)=>{ let t=targetRirFor(e,wi); if(t===''||t==='N/A'||set.rir===''||set.rir==null)return; total++; let diff=Math.abs(num(set.rir)-num(t)); if(diff<=0.5) ok++; else misses.push({w,day:SESS[s][0],name:e.name,set:wi+1,target:t,actual:set.rir}); }); }); } } return {total,ok,misses}; }
  function prRows(){ let rows=[]; function add(name,day,rec){ let bestLoad=0,bestReps=0,bestE=0; (rec.sets||[]).filter(s=>s.type!=='Warmup').forEach(s=>{ bestLoad=Math.max(bestLoad,num(s.load)); bestReps=Math.max(bestReps,num(s.reps)); bestE=Math.max(bestE,(num(s.load))*(1+num(s.reps)/30)); }); if(bestLoad||bestReps||bestE) rows.push({name,day,bestLoad,bestReps,bestE:Math.round(bestE)}); }
    let best={}; for(let w=1;w<=12;w++){ for(let s=0;s<SESS.length;s++){ (BASE[SESS[s][1]]||[]).forEach((e,i)=>{let k=e.name; let rec=state.logs[`w${w}s${s}e${i}`]||{}; let cur={name:e.name,day:SESS[s][0],bestLoad:0,bestReps:0,bestE:0}; (rec.sets||[]).filter(x=>x.type!=='Warmup').forEach(set=>{cur.bestLoad=Math.max(cur.bestLoad,num(set.load));cur.bestReps=Math.max(cur.bestReps,num(set.reps));cur.bestE=Math.max(cur.bestE,num(set.load)*(1+num(set.reps)/30));}); if(cur.bestLoad||cur.bestReps||cur.bestE){let b=best[k]||cur; if(cur.bestE>b.bestE)best[k]=cur; else if(!best[k])best[k]=cur;} }); } } return Object.values(best).sort((a,b)=>b.bestE-a.bestE); }
  const oldRenderAnalytics=renderAnalytics;
  renderAnalytics=function(){ oldRenderAnalytics(); let sec=$('analytics'); if(!sec)return; let rs=rirStats(); let pct=rs.total?Math.round(rs.ok/rs.total*100):0; let pr=prRows(); let html=`<div class=card><div class=title>PR Badges</div><p class=meta>Best logged performances by estimated 1RM.</p><div class=exerciseProgress>${pr.length?pr.slice(0,12).map(r=>`<div class=progressRow><b>🏅 ${E(r.name)}</b><span>${E(r.day)} • Best load: ${r.bestLoad} ${E(state.units||'lb')} • Best reps: ${r.bestReps}</span><span>Best estimated 1RM: ${r.bestE} ${E(state.units||'lb')}</span></div>`).join(''):'<p class=meta>No PRs yet. Log working-set load and reps to populate this section.</p>'}</div></div><div class=card><div class=title>RIR Compliance</div><p class=meta>Compares actual RIR entries against the programmed RIR target. Within 0.5 counts as on target.</p><div class=kpis><div class=kpi><b>${pct}%</b><br><span class=meta>On target</span></div><div class=kpi><b>${rs.total}</b><br><span class=meta>Sets checked</span></div></div><div class=exerciseProgress style="margin-top:10px">${rs.misses.length?rs.misses.slice(0,10).map(m=>`<div class=progressRow><b>${E(m.name)}</b><span>W${m.w} ${E(m.day)} Set ${m.set} • Target RIR ${E(m.target)} • Actual RIR ${E(m.actual)}</span></div>`).join(''):'<p class=meta>No RIR misses logged yet.</p>'}</div></div>`; sec.insertAdjacentHTML('beforeend',html); };
  const oldFlatten=window.flattenRows;
  if(typeof flattenRows==='function'){ const oldF=flattenRows; window.flattenRows=flattenRows=function(){ let rows=oldF(); Object.keys(state.recovery||{}).forEach(k=>{let r=state.recovery[k]||{},m=k.match(/w(\d+)s(\d+)/); if(m)rows.push({Week:m[1],Day:SESS[+m[2]]?SESS[+m[2]][0]:'',Tab:'Recovery',Exercise:'Recovery Check-In',BaseExercise:'',Manual:'',Muscles:'',SetNumber:'',SetType:'Recovery',Load:'',Reps:'',RIR:'',WarmupGuidance:'',WorkingSetTarget:'',RepTarget:'',Rest:'',Notes:`Sleep:${r.sleep||''}; Energy:${r.energy||''}; Soreness:${r.soreness||''}; Stress:${r.stress||''}; ${r.notes||''}`})}); return rows; }; }
  setTimeout(()=>{try{if(!$('workout').classList.contains('hidden'))renderWorkout();}catch(e){}},250);
})();