const BASE={
"Full Body":[
{name:"Lying Leg Curl",warmup:"1-2",sets:"2",reps:"6-8",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Set the machine for the biggest stretch possible at the bottom. Keep hips down.",link:"https://youtu.be/y28L1m1PYUQ",alts:[{name:"Seated Leg Curl",link:"https://youtu.be/oWJBLChYZOQ"},{name:"Nordic Ham Curl",link:"https://youtu.be/UbNb5Tsl46c"}]},
{name:"Squat (Your Choice)",warmup:"2-4",sets:"2",reps:"6-8",rir1:"3",rir2:"2",rest:"3-5 min",notes:"Back squat, front squat, pendulum squat, hack squat, belt squat, or Smith machine squat.",link:"https://youtu.be/v3N4tpPpmyQ",alts:[{name:"Hack Squat",link:"https://youtu.be/0tn5K9NlCfo"},{name:"Leg Press",link:"https://youtu.be/ksBaBSfmZf4"}]},
{name:"Barbell Incline Press",warmup:"2-4",sets:"2",reps:"6-8",rir1:"2",rir2:"1",rest:"3-5 min",notes:"Use a 30° or 45° bench. Pause briefly at the bottom while maintaining pec tension.",link:"https://youtu.be/ad0NL7TH2-I",alts:[{name:"Smith Machine Incline Press",link:"https://youtu.be/q3agRhqt_WA"},{name:"DB Incline Press",link:"https://youtu.be/dhSKkQdUzoA"}]},
{name:"Incline DB Y-Raise",warmup:"0-1",sets:"1",reps:"8-10",rir1:"0",rir2:"N/A",rest:"1-2 min",notes:"Use a 30° incline bench and lift up and out in a Y shape.",link:"https://youtu.be/xaOQJjzNrd8",alts:[{name:"Cable Y-Raise",link:"https://youtu.be/xxnjF6ljHmg"},{name:"Machine Lateral Raise",link:"https://youtu.be/nc6pAci8Tpg"}]},
{name:"Pull-Up (Wide Grip)",warmup:"1-2",sets:"2",reps:"6-8",rir1:"2",rir2:"1",rest:"2-3 min",notes:"Control the negative and use full range of motion.",link:"https://youtu.be/oB27u_w3pX4",alts:[{name:"Lat Pulldown (Wide Grip)",link:"https://youtu.be/nDl3VjkLPQE"},{name:"1-Arm Cable Pulldown",link:"https://youtu.be/01pnZt1uVFI"}]},
{name:"Standing Calf Raise",warmup:"0-1",sets:"1",reps:"6-8",rir1:"0",rir2:"N/A",rest:"1-2 min",notes:"Pause 1-2 seconds at the bottom of each rep.",link:"https://youtu.be/WMkCGNwo5ts",alts:[{name:"Leg Press Calf Press",link:"https://youtu.be/-mcxziH_KdM"},{name:"Donkey Calf Raise",link:"https://youtu.be/LC9SO-pIXqA"}]}
],
"Upper":[
{name:"Close-Grip Lat Pulldown",warmup:"2-3",sets:"2",reps:"8-10",rir1:"2",rir2:"1",rest:"2-3 min",notes:"Lean back slightly and drive elbows down.",link:"https://youtu.be/7l859qd4E48",alts:[{name:"Close-Grip Pull-Up",link:"https://youtu.be/3DnqKKfz6wY"},{name:"1-Arm Cable Pulldown",link:"https://youtu.be/01pnZt1uVFI"}]},
{name:"Chest-Supported T-Bar Row",warmup:"2-3",sets:"2",reps:"8-10",rir1:"2",rir2:"1",rest:"2-3 min",notes:"Flare elbows roughly 45° and squeeze shoulder blades together.",link:"https://youtu.be/-FAxUZoPDc4",alts:[{name:"Chest-Supported Machine Row",link:"https://youtu.be/QZ7VZpjNTG8"},{name:"Chest-Supported DB Row",link:"https://youtu.be/Cmcv44jiQd0"}]},
{name:"Machine Shrug",warmup:"1-2",sets:"1",reps:"6-8",rir1:"1",rir2:"N/A",rest:"1-2 min",notes:"Shrug up to your ears. Use straps if possible.",link:"https://youtu.be/2KDc6iAcrAw",alts:[{name:"Barbell Shrug",link:"https://youtu.be/CQDTdasj9BA"},{name:"Cable Shrug-In",link:"https://youtu.be/0EqU6-o3PAw"}]},
{name:"Machine Chest Press",warmup:"2-4",sets:"2",reps:"8-10",rir1:"2",rir2:"1",rest:"3-5 min",notes:"Pause one second at the bottom while keeping pec tension.",link:"https://youtu.be/qTSTOVVr8rU",alts:[{name:"Smith Machine Bench Press",link:"https://youtu.be/cJ8JrXUQ3xQ"},{name:"DB Bench Press",link:"https://youtu.be/qmyToaabqdQ"}]},
{name:"High-Cable Lateral Raise",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Set cable around hip height and get a deep side-delt stretch.",link:"https://youtu.be/DX1WzS7k0Uc",alts:[{name:"DB Lateral Raise",link:"https://youtu.be/Z8OrSIk_574"},{name:"Machine Lateral Raise",link:"https://youtu.be/nc6pAci8Tpg"}]},
{name:"1-Arm Reverse Pec Deck",warmup:"0-1",sets:"1",reps:"8-10",rir1:"0",rir2:"N/A",rest:"1-2 min",notes:"Sweep the weight out in the largest semi-circle possible.",link:"https://youtu.be/WkI6IHmYORY",alts:[{name:"Lying Reverse DB Flye",link:"https://youtu.be/MXGZHJFQ9bE"},{name:"Reverse Cable Crossover",link:"https://youtu.be/STZ3Twq5fgc"}]},
{name:"Cable Crunch",warmup:"0-1",sets:"2",reps:"6-8",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Round your lower back and maintain ab connection.",link:"https://youtu.be/LvJM9V3D_CQ",alts:[{name:"Weighted Crunch",link:"https://youtu.be/Q_n8cSQLhog"},{name:"Machine Crunch",link:"https://youtu.be/KlxdhDSi5Dc"}]}
],
"Lower":[
{name:"Leg Extension",warmup:"1-2",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Set the seat back far while staying comfortable. Pull yourself into the seat.",link:"https://youtu.be/G0_M9LBCT0o",alts:[{name:"Reverse Nordic",link:"https://youtu.be/aHS9tKzJXik"},{name:"Sissy Squat",link:"https://youtu.be/Ma99aw-VDJQ"}]},
{name:"Barbell RDL",warmup:"2-3",sets:"2",reps:"6-8",rir1:"3",rir2:"2",rest:"2-3 min",notes:"Hinge back, keep bar over midfoot, and maintain a neutral spine.",link:"https://youtu.be/xbnan2iNh-Q",alts:[{name:"DB RDL",link:"https://youtu.be/CaryZp20CuI"},{name:"Seated Cable Deadlift",link:"https://youtu.be/FCe6PIQbB-s"}]},
{name:"Machine Hip Thrust",warmup:"2-4",sets:"2",reps:"6-8",rir1:"2",rir2:"1",rest:"2-3 min",notes:"Squeeze glutes at the top and control the descent.",link:"https://youtu.be/ELgSmlwFsFQ",alts:[{name:"Barbell Hip Thrust",link:"https://youtu.be/8RwbLtfLu6A"},{name:"45° Hyperextension",link:"https://youtu.be/1Rr1-FW6ZJs"}]},
{name:"Leg Press",warmup:"2-4",sets:"1",reps:"6-8",rir1:"1",rir2:"N/A",rest:"2-3 min",notes:"Feet lower for quad focus. Go deep without excessive back rounding.",link:"https://youtu.be/ksBaBSfmZf4",alts:[{name:"Smith Machine Squat",link:"https://youtu.be/wSHxfQJe1ic"},{name:"Barbell Squat",link:"https://youtu.be/UGwmUJkTIx8"}]},
{name:"Standing Calf Raise",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Pause 1-2 seconds at the bottom.",link:"https://youtu.be/WMkCGNwo5ts",alts:[{name:"Leg Press Calf Press",link:"https://youtu.be/-mcxziH_KdM"},{name:"Donkey Calf Raise",link:"https://youtu.be/LC9SO-pIXqA"}]}
],
"Arms/Delts":[
{name:"Bayesian Cable Curl",warmup:"0-1",sets:"2",reps:"6-8",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Control the negative and feel a deep stretch.",link:"https://youtu.be/_w_Uan2dG-4",alts:[{name:"Incline DB Curl",link:"https://youtu.be/Nf1_Ok0LDcI"},{name:"Standing DB Curl",link:"https://youtu.be/vneVQlN7LR4"}]},
{name:"Overhead Cable Triceps Extension",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Feel a deep triceps stretch throughout the negative.",link:"https://youtu.be/7GvY7yTEepM",alts:[{name:"Overhead DB Triceps Extension",link:"https://youtu.be/5KX0EjOTMaI"},{name:"Skull Crusher",link:"https://youtu.be/1n6xrEI5g0Q"}]},
{name:"Modified Zottman Curl",warmup:"0-1",sets:"1",reps:"8-10",rir1:"0",rir2:"N/A",rest:"1-2 min",notes:"Hammer curl up, supinated curl down.",link:"https://youtu.be/J0l0qQCy80Q",alts:[{name:"DB Hammer Curl",link:"https://youtu.be/AS4FeNiHyKg"},{name:"Preacher Hammer Curl",link:"https://youtu.be/sInGFVj-bJA"}]},
{name:"Cable Triceps Kickback",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Keep upper arm behind torso throughout.",link:"https://youtu.be/FGJ64JyKod0",alts:[{name:"Seated Dip Machine",link:"https://youtu.be/BRueufxDP2Q"},{name:"Close-Grip Dip",link:"https://youtu.be/G7bonPtkitM"}]},
{name:"DB Wrist Curl",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Smooth, controlled reps.",link:"https://youtu.be/HJx1sIZKDqk",alts:[{name:"Cable Wrist Curl",link:"https://youtu.be/S9NEwbiYEBE"}]},
{name:"DB Wrist Extension",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Smooth, controlled reps.",link:"https://youtu.be/uCAoI5FnLhs",alts:[{name:"Cable Wrist Extension",link:"https://youtu.be/_KI-O0zMv60"}]},
{name:"Alternating DB Curl",warmup:"0-1",sets:"1",reps:"6-8",rir1:"0",rir2:"N/A",rest:"1-2 min",notes:"Slow, controlled reps.",link:"https://youtu.be/kSxgX6HIYxQ",alts:[{name:"Barbell Curl",link:"https://youtu.be/UvxrIuG-Xeg"},{name:"EZ-Bar Curl",link:"https://youtu.be/wXjPZdhUzBQ"}]},
{name:"Machine Lateral Raise",warmup:"0-1",sets:"2",reps:"8-10",rir1:"1",rir2:"0",rest:"1-2 min",notes:"Focus on squeezing your side delt.",link:"https://youtu.be/nc6pAci8Tpg",alts:[{name:"High-Cable Lateral Raise",link:"https://youtu.be/DX1WzS7k0Uc"},{name:"DB Lateral Raise",link:"https://youtu.be/Z8OrSIk_574"}]},
{name:"Dead Hang (optional)",warmup:"0-1",sets:"2",reps:"N/A",rir1:"0",rir2:"0",rest:"1-2 min",notes:"Try to add a few more seconds each week.",link:"https://youtu.be/5M8uPbfQsbg",alts:[]}
]};
const SESS=[["Full","Full Body"],["Upper","Upper"],["Lower","Lower"],["Arms","Arms/Delts"]];
const THEMES={night:{name:"Night",bg:"#070b12",bg2:"#0c1220",card:"#111827",card2:"#151f31",ink:"#f3f7ff",muted:"#9aa6b8",line:"#263247",button:"#121d2e",buttonText:"#f3f7ff",active:"#6b48c8",active2:"#2e63bb",field:"#0b111c",link:"#b9d2ff",banner:"#0d1625",pill:"#182437"},forest:{name:"Forest",bg:"#07110d",bg2:"#0e1f17",card:"#12251c",card2:"#182f23",ink:"#effcf3",muted:"#9cb6a6",line:"#294735",button:"#183a2a",buttonText:"#effcf3",active:"#2f9e6b",active2:"#166448",field:"#0a1812",link:"#a7f3c8",banner:"#0d2118",pill:"#1a3528"},ember:{name:"Ember",bg:"#140b08",bg2:"#24110b",card:"#2a1811",card2:"#341d14",ink:"#fff6ef",muted:"#c6a99a",line:"#563426",button:"#3a2016",buttonText:"#fff6ef",active:"#d45a2a",active2:"#8f2f1a",field:"#1c0f0a",link:"#ffc7a8",banner:"#24130d",pill:"#3a2117"},slate:{name:"Slate",bg:"#0f172a",bg2:"#111827",card:"#1f2937",card2:"#273244",ink:"#f8fafc",muted:"#a6b0c0",line:"#3c4a60",button:"#263244",buttonText:"#f8fafc",active:"#64748b",active2:"#475569",field:"#111827",link:"#dbeafe",banner:"#172033",pill:"#263244"},light:{name:"Light",bg:"#f4f0e8",bg2:"#ebe3d5",card:"#fffaf1",card2:"#f7eddd",ink:"#172033",muted:"#687386",line:"#d9cbbb",button:"#fffaf1",buttonText:"#172033",active:"#6b5bd6",active2:"#2f6db5",field:"#ffffff",link:"#244f9e",banner:"#f1e6d5",pill:"#ede2d2"}};
let state={week:1,session:0,logs:{},bw:{},units:"lb",swaps:{},custom:{},theme:"night",customTheme:null};
function $(id){return document.getElementById(id)}function day(){return SESS[state.session][1]}function exs(){return BASE[day()]||[]}function dayKey(){return `w${state.week}s${state.session}`}function baseKey(i){return `${dayKey()}e${i}`}function customKey(i){return `${dayKey()}c${i}`}function toast(t){$("toast").textContent=t;$("toast").className="toast show";setTimeout(()=>$("toast").className="toast",1300)}
function save(show){localStorage.setItem("rookieMinMax",JSON.stringify(state));if(show)toast("Saved")}function load(){try{state=Object.assign(state,JSON.parse(localStorage.getItem("rookieMinMax")||"{}"))}catch(e){}if(!state.swaps)state.swaps={};if(!state.custom)state.custom={};if(!state.theme)state.theme="night"}
function applyTheme(){let t=state.customTheme||THEMES[state.theme]||THEMES.night;Object.keys(THEMES.night).forEach(k=>{if(k!=="name"&&t[k])document.documentElement.style.setProperty("--"+k,t[k])});document.querySelector('meta[name="theme-color"]').setAttribute("content",t.bg||"#070b12")}
function opts(e){return [{name:e.name,link:e.link||""}].concat((e.alts||[]).filter(a=>a.name))}function cur(e,k){return opts(e)[+(state.swaps[k]||0)]||opts(e)[0]}function lnk(t,u){return u?`<a target=_blank rel=noopener href="${u}">${t}</a>`:`<span class=nolink>${t}</span>`}
function plannedWarmups(e){let m=String(e.warmup||"0").match(/\d+/);return m?+m[0]:0}function workingCount(e){return Math.max(1,+e.sets||1)}function defaultSets(e){let a=[];for(let i=0;i<plannedWarmups(e);i++)a.push({type:"Warmup",load:"",reps:"",rir:""});for(let i=0;i<workingCount(e);i++)a.push({type:"Working",load:"",reps:"",rir:i===0?e.rir1:(e.rir2||"")});return a}
function rec(k,e){let r=state.logs[k]||{};if(!r.sets){r.sets=defaultSets(e);if(r.l1||r.r1||r.rir1){let first=r.sets.find(x=>x.type==="Working")||r.sets[0];first.load=r.l1||"";first.reps=r.r1||"";first.rir=r.rir1||first.rir||""}if(r.l2||r.r2||r.rir2){let work=r.sets.filter(x=>x.type==="Working")[1];if(work){work.load=r.l2||"";work.reps=r.r2||"";work.rir=r.rir2||work.rir||""}}}state.logs[k]=r;return r}
window.weekStep=d=>{state.week=Math.min(12,Math.max(1,state.week+d));renderWorkout();save()};window.setSession=i=>{state.session=i;renderWorkout();save()};window.sw=(i,v)=>{state.swaps[baseKey(i)]=+v;save();renderWorkout()};window.toggleTheme=()=>show("settings",true);
window.addSet=(k,type)=>{let r=state.logs[k];if(!r)return;r.sets.push({type,load:"",reps:"",rir:""});save();renderWorkout()};window.removeSet=(k,n)=>{let r=state.logs[k];if(!r)return;r.sets.splice(n,1);save();renderWorkout()};window.setField=(k,n,f,v)=>{state.logs[k].sets[n][f]=v;save()};window.noteField=(k,v)=>{state.logs[k].notes=v;save()};
function setRows(k,r){return r.sets.map((s,n)=>`<div class=setRow><div class=setHead><b>Set ${n+1}</b><span class=setType>${s.type}</span></div><div class=setInputs><div><label>Load</label><input inputmode=decimal value="${s.load||''}" oninput="setField('${k}',${n},'load',this.value)"></div><div><label>Reps</label><input inputmode=numeric value="${s.reps||''}" oninput="setField('${k}',${n},'reps',this.value)"></div><div><label>RIR</label><input inputmode=decimal value="${s.rir||''}" oninput="setField('${k}',${n},'rir',this.value)"></div></div><button class="miniBtn danger" style="width:100%;margin-top:8px" onclick="removeSet('${k}',${n})">Remove Set</button></div>`).join("")}
function choices(e,i,k){let o=opts(e),sel=+(state.swaps[k]||0);if(o.length<2)return"";let h=`<label style="margin-top:12px">Exercise Choice</label><select class=choice onchange="sw(${i},this.value)">`;o.forEach((x,n)=>h+=`<option value="${n}" ${n==sel?'selected':''}>${n?'Alt: ':'Main: '}${x.name}</option>`);return h+`</select>`}
function links(e){let o=opts(e),h='<div class=links>'+lnk('Main demo: '+e.name,e.link)+'</div>';if(o.length>1){h+='<div class=altTitle>Alternates</div><div class=links>';o.slice(1).forEach(a=>h+=lnk(a.name,a.link));h+='</div>'}return h}
function renderExercise(e,i,k,isManual){let r=rec(k,e),c=isManual?e:cur(e,k);return `<div class=card><div class=title>${c.name}</div><div><span class=pill>Warmup ${e.warmup||0}</span><span class=pill>${e.sets||1} working</span><span class=pill>${e.reps||''} reps</span><span class=pill>${e.rest||''}</span></div>${!isManual?choices(e,i,k):''}${setRows(k,r)}<div class=setActions><button class=miniBtn onclick="addSet('${k}','Warmup')">+ Warmup Set</button><button class=miniBtn onclick="addSet('${k}','Working')">+ Working Set</button></div><button class=miniBtn style="width:100%;margin-top:8px" onclick="addSet('${k}','Extra')">+ Extra Set</button><label style="margin-top:12px">Notes</label><textarea oninput="noteField('${k}',this.value)">${r.notes||''}</textarea>${!isManual?links(e):''}<p class=meta>${e.notes||''}</p>${isManual?`<button class="miniBtn danger" style="width:100%;margin-top:8px" onclick="deleteManual(${i})">Delete Manual Exercise</button>`:''}</div>`}
window.addManual=()=>{let name=$("manualName").value.trim();if(!name){toast("Enter exercise name");return}let obj={name,warmup:$("manualWarmup").value||"0",sets:$("manualSets").value||"1",reps:$("manualReps").value||"",rir1:"",rir2:"",rest:$("manualRest").value||"",notes:$("manualNotes").value||"",link:"",alts:[]};let k=dayKey();state.custom[k]=state.custom[k]||[];state.custom[k].push(obj);save(true);renderWorkout()};window.deleteManual=i=>{let k=dayKey();(state.custom[k]||[]).splice(i,1);save(true);renderWorkout()};
function manualForm(){return `<div class=card><div class=title>Add Manual Exercise</div><div class=manualGrid style="margin-top:10px"><div><label>Name</label><input id=manualName placeholder="Exercise name"></div><div><label>Warmups</label><input id=manualWarmup inputmode=numeric placeholder="0"></div><div><label>Working Sets</label><input id=manualSets inputmode=numeric placeholder="1"></div><div><label>Target Reps</label><input id=manualReps placeholder="8-10"></div><div><label>Rest</label><input id=manualRest placeholder="1-2 min"></div><div><label>Notes</label><input id=manualNotes placeholder="Optional"></div></div><button class=primary style="width:100%;margin-top:10px" onclick="addManual()">Add Exercise</button></div>`}
function renderWorkout(){let h=`<div class=savebar><button class=primary onclick="save(true)">Save Workout</button></div><div class=card><label>Week</label><div class=weekbar><button onclick="weekStep(-1)">‹</button><div class=weekbox><span>Week</span><b>${state.week}</b></div><button onclick="weekStep(1)">›</button></div><label style="margin-top:12px">Workout Day</label><div class=dayrow>`;SESS.forEach((s,i)=>h+=`<button class="${i===state.session?'active':''}" onclick="setSession(${i})">${s[0]}</button>`);h+=`</div><div style="margin-top:12px"><label>Bodyweight (${state.units})</label><input inputmode=decimal value="${state.bw[state.week]||''}" oninput="state.bw[state.week]=this.value;save()" placeholder="Optional"></div></div>`;h+=manualForm();exs().forEach((e,i)=>h+=renderExercise(e,i,baseKey(i),false));(state.custom[dayKey()]||[]).forEach((e,i)=>h+=renderExercise(e,i,customKey(i),true));$("workout").innerHTML=h}
function trainingSets(r){return (r.sets||[]).filter(s=>s.type!=="Warmup")}function maxLoad(r){return Math.max(0,...trainingSets(r).map(s=>+s.load||0))}function volOf(r){return trainingSets(r).reduce((a,s)=>a+(+s.load||0)*(+s.reps||0),0)}function bestE1(r){return Math.max(0,...trainingSets(r).map(s=>(+s.load||0)*(1+(+s.reps||0)/30)))}
function volume(){let v=Array(12).fill(0);for(let w=1;w<=12;w++)for(let s=0;s<SESS.length;s++){(BASE[SESS[s][1]]||[]).forEach((e,i)=>v[w-1]+=volOf(state.logs[`w${w}s${s}e${i}`]||{}));(state.custom[`w${w}s${s}`]||[]).forEach((e,i)=>v[w-1]+=volOf(state.logs[`w${w}s${s}c${i}`]||{}))}return v}
function chart(vals){let c=document.createElement("canvas"),ctx=c.getContext("2d");setTimeout(()=>{let w=c.width=c.clientWidth*2,h=c.height=210*2,p=36,m=Math.max(1,...vals);ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--line');ctx.lineWidth=2;for(let g=0;g<4;g++){let y=p+(h-p*2)*g/3;ctx.beginPath();ctx.moveTo(p,y);ctx.lineTo(w-p,y);ctx.stroke()}ctx.strokeStyle=getComputedStyle(document.documentElement).getPropertyValue('--active');ctx.lineWidth=5;ctx.beginPath();vals.forEach((v,i)=>{let x=p+(w-p*2)*i/11,y=h-p-(h-p*2)*v/m;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();ctx.fillStyle=getComputedStyle(document.documentElement).getPropertyValue('--muted');ctx.font='22px -apple-system';vals.forEach((v,i)=>{if(i%2===0)ctx.fillText('W'+(i+1),p+(w-p*2)*i/11-10,h-10)})},20);return c}
function exerciseProgress(){let rows=[];function collect(name,day,fn){let pts=[];for(let w=1;w<=12;w++){let r=fn(w),m=maxLoad(r);if(m>0)pts.push({w,m})}if(pts.length){let first=pts[0],last=pts[pts.length-1],best=Math.max(...pts.map(p=>p.m));rows.push({name,day,first:first.m,firstW:first.w,last:last.m,lastW:last.w,best,change:last.m-first.m})}}SESS.forEach((s,si)=>(BASE[s[1]]||[]).forEach((e,ei)=>collect(e.name,s[0],w=>state.logs[`w${w}s${si}e${ei}`]||{})));Object.keys(state.custom).forEach(k=>(state.custom[k]||[]).forEach((e,i)=>{let m=k.match(/w(\d+)s(\d+)/);if(m)collect(e.name,SESS[+m[2]][0],w=>state.logs[`w${w}s${m[2]}c${i}`]||{})}));rows.sort((a,b)=>b.change-a.change||b.best-a.best);return rows}
function renderAnalytics(){let vols=volume(),total=Math.round(vols.reduce((a,b)=>a+b,0)),best=0;Object.values(state.logs).forEach(r=>best=Math.max(best,bestE1(r)));let rows=exerciseProgress();let h=`<div class=card><div class=title>Analytics</div><p class=meta>Training volume excludes warmup sets. Stats update from logs saved on this phone/browser.</p></div><div class=kpis><div class=kpi><b>${total}</b><br><span class=meta>Total working volume</span></div><div class=kpi><b>${Math.round(best)}</b><br><span class=meta>Best e1RM</span></div></div><div class=card><div class=title>Weekly Volume</div><div id=volChart></div></div><div class=card><div class=title>Bodyweight</div><div id=bwChart></div></div><div class=card><div class=title>Weight Increase by Exercise</div><p class=meta>Compares first recorded training-set load to latest recorded training-set load.</p><div class=exerciseProgress>`;h+=rows.length?rows.map(r=>`<div class=progressRow><b>${r.name}</b><span>${r.day} • first: ${r.first} ${state.units} (W${r.firstW}) → latest: ${r.last} ${state.units} (W${r.lastW})</span><span>Change: ${r.change>=0?'+':''}${r.change} ${state.units} • Best: ${r.best} ${state.units}</span></div>`).join(''):'<p class=meta>No logged lifting weight yet.</p>';h+=`</div></div>`;$("analytics").innerHTML=h;$("volChart").appendChild(chart(vols));$("bwChart").appendChild(chart(Array.from({length:12},(_,i)=>+state.bw[i+1]||0)))}
function renderPlan(){let h='<div class=card><div class=title>Plan + Links</div><p class=meta>Exercises from the original Excel file with warmup guidance and alternate options.</p></div>';SESS.forEach(s=>{h+=`<div class=card><div class=title>${s[1]}</div></div>`;(BASE[s[1]]||[]).forEach(e=>h+=`<div class=card><div class=title>${e.name}</div><div><span class=pill>Warmup ${e.warmup}</span><span class=pill>${e.sets} working</span><span class=pill>${e.reps} reps</span><span class=pill>${e.rest}</span></div><p class=meta>${e.notes||''}</p>${links(e)}</div>`)});$("plan").innerHTML=h}
function setTheme(name){state.theme=name;state.customTheme=null;applyTheme();renderSettings();save(true)}window.setTheme=setTheme;window.setCustom=(k,v)=>{let t=Object.assign({},THEMES[state.theme]||THEMES.night,state.customTheme||{});t[k]=v;state.customTheme=t;applyTheme();save()};function colorInput(label,key){let t=state.customTheme||THEMES[state.theme]||THEMES.night;return `<div class=swatch><input type=color value="${t[key]}" oninput="setCustom('${key}',this.value)"><div><label>${label}</label><span class=meta>${key}</span></div></div>`}
function renderSettings(){let h=`<div class=card><div class=title>Colour Scheme</div><p class=meta>Choose a preset, or customize individual page colours.</p><div class=palette>`;Object.keys(THEMES).forEach(k=>h+=`<button class="${!state.customTheme&&state.theme===k?'active':''}" onclick="setTheme('${k}')">${THEMES[k].name}</button>`);h+=`</div></div><div class=card><div class=title>Custom Palette</div><div class=colorgrid>${colorInput('Font','ink')}${colorInput('Background','bg')}${colorInput('Background 2','bg2')}${colorInput('Cards','card')}${colorInput('Card Gradient','card2')}${colorInput('Banners','banner')}${colorInput('Buttons','button')}${colorInput('Active Buttons/Tabs','active')}${colorInput('Button Gradient','active2')}${colorInput('Input Fields','field')}${colorInput('Borders','line')}${colorInput('Links/Pills','link')}${colorInput('Secondary Text','muted')}${colorInput('Pill Background','pill')}</div></div><div class=card><div class=title>Backup + Settings</div><p class=meta>Data saves locally on this phone/browser. Export a backup occasionally.</p><label>Units</label><select onchange="state.units=this.value;save(true);renderWorkout()"><option ${state.units==='lb'?'selected':''}>lb</option><option ${state.units==='kg'?'selected':''}>kg</option></select><button class=primary style="width:100%;margin-top:12px" onclick="save(true)">Save Now</button><button style="width:100%;margin-top:8px" onclick=exportData()>Export Backup</button><button style="width:100%;margin-top:8px" onclick="$('importer').click()">Import Backup</button></div>`;$("settings").innerHTML=h}
function exportData(){let a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.download="minmax-backup.json";a.click()}$("importer").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{state=JSON.parse(r.result);if(!state.swaps)state.swaps={};if(!state.custom)state.custom={};save();applyTheme();renderAll();toast("Imported")};r.readAsText(f)};
function show(v){["workout","plan","analytics","settings"].forEach(x=>$(x).classList.toggle("hidden",x!==v));document.querySelectorAll(".bottom button").forEach(b=>b.classList.toggle("active",b.dataset.v===v));if(v==="workout")renderWorkout();if(v==="plan")renderPlan();if(v==="analytics")renderAnalytics();if(v==="settings")renderSettings();scrollTo(0,0)}document.querySelectorAll(".bottom button").forEach(b=>b.onclick=()=>show(b.dataset.v));function renderAll(){renderWorkout();renderPlan();renderAnalytics();renderSettings()}load();applyTheme();renderAll();